language: node_js
node_js:
- '5'

before_deploy:
- npm run build

deploy:
  provider: npm
  email: serveradmin@octoblu.com
  api_key:
    secure: G3kBMJOFkTKH4lnkbIhil7t66Me5WeOsP2X+KDl2QfWfC9VYGT75QM+wFu58+Xgsai156TSbJs71atY8Wp0TPuU8h9ogv8E3e8wQPT4/M+iLLXQUhxbQ2+VkPGj1ml5UdlclPNmrGinwXdo9i974vBXYTxRBjLs55Q911wDKyfKeBltTzdWDRpQLITAuvmlUFIhSO7brqdJ21vhChOJHZkg4nBvfrRzQv46LlKLMWqiXxuWP1pnKPYtFxLa3W6f3mDgFMI+nAhOdd7SmRV5pCn0zxham2ghVQh1z7yheMQOcB2Gx0GpgsWSWDmhbtFY6zR2cnB9WB8WKrGRrQNc3Yeh7enpFQreQ0iBvnJhracXENo83vkYeopiNdeO5FS3q/hy8cCUHxp4m9RscF3yuZMkg/l7aRSRospg4W8Vw4z96j8fcVhW8GwNnv29EUlWB2Zn/22aGSnwD9o4cAjTuX8sxBd9hv4OQtkHjeGtFjPQjI1oqDuA46FcSoM/KDcs/+cLQfhcDEmj3ksMbrmFgnqFyvm/8V57eGKdoVuW15eVcqKQHzCCtwau+WSwTTffBZ+pijKFFbZvvYCxo5AKiyQwE0bVqVtBpH6+b7T3kKR2sVRopxTO6zmQYzuYMQDwfDnVR2YunJN/zGsfPycA4b8+nkAbk6ERvjo77BjcEidE=
  on:
    tags: true
